### ISSUE TITLE
Booru context accessed outside of scope

### ISSUE THREAD

**Issue by halomakes** [halomademeapc/ChatBeet#61]
# Booru context accessed outside of scope

## Issue area
[X] General Rules
[ ] Stats
[ ] Personalization
[ ] WebUI
[ ] Other:  `[area]`

## Steps to Reproduce

1. Invoke booru command

## Actual behavior
19:51:41 -ChatBeet- Encountered ObjectDisposedException from Microsoft.EntityFrameworkCore
19:51:41 <ChatBeet> Base ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of d
19:51:41 <ChatBeet>    at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
19:51:41 <ChatBeet>    at Microsoft.EntityFrameworkCore.DbContext.AddRange(IEnumerable`1 entities)
19:51:41 <ChatBeet>    at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.AddRange(IEnumerable`1 entities)
19:51:41 <ChatBeet>    at ChatBeet.Services.BooruService.RecordTags(String nick, IEnumerable`1 tags) in /src/ChatBeet/Services/BooruService.cs:line 131

## Insults
Fire and forget bad! Bad carrots!

**Comment by halomakes** [comment]
Resolved by https://github.com/halomademeapc/GravyBot/commit/35ebf453e6231f79eaf5126f9bbba0f2da9ff9fc
